# Generated by Django 4.1.2 on 2022-11-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='raring',
            new_name='rating',
        ),
    ]
